# Jake Herron
# 005113997
# jakeh524@gmail.com

default: lab1a.c
	gcc -Wall -Wextra -g lab1a.c -o lab1a
	
clean:
	rm lab1a
	rm lab1a-005113997.tar.gz
	
dist:
	tar -cvzf lab1a-005113997.tar.gz lab1a.c Makefile README
