# Jake Herron
# 005113997
# jakeh524@gmail.com

default: lab4b.c
	gcc -Wall -Wextra -g -lmraa -lm lab4b.c -o lab4b
	
clean: default
	rm lab4b
	rm lab4b-005113997.tar.gz
	
dist:
	tar -cvzf lab4b-005113997.tar.gz lab4b.c Makefile README

check: 
